param(
    [string]$JavaApiBaseUrl = "http://127.0.0.1:8088/api",
    [string]$TemplateKey = ""
)

$ErrorActionPreference = "Stop"

$baseUrl = $JavaApiBaseUrl.TrimEnd("/")
if ([string]::IsNullOrWhiteSpace($TemplateKey)) {
    $TemplateKey = "workflow_runtime_lite_smoke_{0}" -f ([DateTimeOffset]::Now.ToUnixTimeSeconds())
}

function Invoke-JsonPost {
    param(
        [string]$Url,
        [object]$Payload
    )

    $json = $Payload | ConvertTo-Json -Depth 40
    return Invoke-RestMethod -Method Post -Uri $Url -Body $json -ContentType "application/json" -TimeoutSec 45
}

function Assert-ApiResponse {
    param(
        [object]$Response,
        [string]$StepName
    )

    if (-not $Response.success) {
        throw "$StepName failed: $($Response.message)"
    }
}

$payload = [ordered]@{
    workflowTemplateKey = $TemplateKey
    name = "Runtime Lite Smoke Workflow"
    description = "Verifies Workflow Runtime Lite with CodeAgent, Human Approval and Report Generator."
    nodes = @(
        [ordered]@{
            nodeId = "product_1"
            agentKey = "product"
            name = "Product Agent"
            position = [ordered]@{ x = 80; y = 80 }
            input_fields = @("requirement")
            output_fields = @("product_result")
            stage = "analysis"
            enabled = $true
            description = "Runtime Lite simulated product node"
        },
        [ordered]@{
            nodeId = "code_agent_2"
            agentKey = "code_agent"
            name = "CodeAgent Folder Apply"
            position = [ordered]@{ x = 360; y = 80 }
            input_fields = @("product_result")
            output_fields = @("code_agent_result")
            stage = "code_ops"
            enabled = $true
            description = "Runtime Lite executed CodeAgent folder node"
            codeAgentConfig = [ordered]@{
                operation = "apply_folder_changes"
                target_path = "output/code_agent_workspace"
                includePatterns = "**/*.md, **/*.txt"
                excludePatterns = ".env, .git/**, node_modules/**, dist/**, target/**"
                outputFile = "runtime_lite_smoke_result.md"
                content = "# Runtime Lite Smoke Result`n`nThis file was generated by Workflow Runtime Lite smoke test."
                dryRun = $false
                backupBeforeWrite = $true
            }
        },
        [ordered]@{
            nodeId = "human_3"
            agentKey = "human_approval"
            nodeType = "human_approval"
            name = "Human Approval"
            position = [ordered]@{ x = 640; y = 80 }
            input_fields = @("code_agent_result")
            output_fields = @("approval_result")
            stage = "approval"
            enabled = $true
            description = "Runtime Lite waiting approval node"
            humanApprovalConfig = [ordered]@{
                question = "是否确认 Runtime Lite 文件夹变更演示结果？"
                approveLabel = "批准"
                rejectLabel = "拒绝"
                required = $true
            }
        },
        [ordered]@{
            nodeId = "report_4"
            agentKey = "report"
            name = "Report Generator"
            position = [ordered]@{ x = 920; y = 80 }
            input_fields = @("workflow_events")
            output_fields = @("report_path")
            stage = "report"
            enabled = $true
            description = "Runtime Lite executed report node"
        }
    )
    connections = @(
        [ordered]@{ fromNodeId = "product_1"; toNodeId = "code_agent_2" },
        [ordered]@{ fromNodeId = "code_agent_2"; toNodeId = "human_3" },
        [ordered]@{ fromNodeId = "human_3"; toNodeId = "report_4" }
    )
    version = "1.0"
}

$saveResponse = Invoke-JsonPost -Url "$baseUrl/platform/workflows/templates" -Payload $payload
Assert-ApiResponse -Response $saveResponse -StepName "save runtime lite workflow template"

$executeResponse = Invoke-JsonPost `
    -Url "$baseUrl/platform/workflows/templates/$TemplateKey/execute" `
    -Payload @{
        input_data = @{
            requirement = "Runtime Lite smoke: execute CodeAgent folder operation, wait for approval and generate report"
            runtime_mode = "workflow_runtime_lite"
        }
    }
Assert-ApiResponse -Response $executeResponse -StepName "execute runtime lite workflow"

$platformRunId = $executeResponse.data.platformRunId
$replayResponse = Invoke-RestMethod -Method Get -Uri "$baseUrl/platform/runs/$platformRunId/replay" -TimeoutSec 45
Assert-ApiResponse -Response $replayResponse -StepName "get runtime lite replay"

$events = @($replayResponse.data.events)
$eventTypes = @($events | ForEach-Object { $_.eventType })
$agents = @($events | ForEach-Object { $_.agent } | Where-Object { -not [string]::IsNullOrWhiteSpace($_) })
$runSummary = $replayResponse.data.runSummary
$uiViewModel = $replayResponse.data.uiViewModel
$runtimeSummary = $uiViewModel.runtime_summary

$approvalResponse = Invoke-JsonPost `
    -Url "$baseUrl/platform/runs/$platformRunId/approval" `
    -Payload @{
        approved = $true
        comment = "Runtime Lite smoke approval"
    }
Assert-ApiResponse -Response $approvalResponse -StepName "approve runtime lite run"

$approvedReplayResponse = Invoke-RestMethod -Method Get -Uri "$baseUrl/platform/runs/$platformRunId/replay" -TimeoutSec 45
Assert-ApiResponse -Response $approvedReplayResponse -StepName "get approved runtime lite replay"

$success = -not [string]::IsNullOrWhiteSpace($platformRunId) `
    -and $replayResponse.data.status -eq "WAITING_FOR_HUMAN" `
    -and $approvedReplayResponse.data.status -eq "APPROVED" `
    -and ($eventTypes -contains "WORKFLOW_STARTED") `
    -and ($eventTypes -contains "HUMAN_APPROVAL_REQUIRED") `
    -and ($eventTypes -contains "REPORT_GENERATED") `
    -and ($agents -contains "code_agent") `
    -and ($agents -contains "report") `
    -and -not [string]::IsNullOrWhiteSpace($runSummary.report_path) `
    -and $runtimeSummary.node_counts.executed -ge 1 `
    -and $runtimeSummary.node_counts.simulated -ge 1 `
    -and $runtimeSummary.node_counts.waiting -ge 1

$deleteResponse = Invoke-RestMethod -Method Delete -Uri "$baseUrl/platform/workflows/templates/$TemplateKey" -TimeoutSec 30
Assert-ApiResponse -Response $deleteResponse -StepName "delete runtime lite workflow template"

$summary = [ordered]@{
    success = $success
    templateKey = $TemplateKey
    platformRunId = $platformRunId
    initialStatus = $replayResponse.data.status
    approvedStatus = $approvedReplayResponse.data.status
    reportPath = $runSummary.report_path
    runtimeSummary = $runtimeSummary
    eventTypes = $eventTypes
    agents = $agents
}

$summary | ConvertTo-Json -Depth 30

if (-not $success) {
    throw "Workflow Runtime Lite smoke test failed"
}
